class Log:
    def __init__(self):
        self.x = []
        self.y = []
        self.z = []
        self.v = []
        self.v_demand = []
        self.yaw = []
        self.pitch = []
        self.yaw_demand = []
        self.pitch_demand = []
        self.measurement = []
        self.loc_pos = []
        self.sat_time_stamps = []
        self.x_demand = []
        self.y_demand = []
        self.z_demand = []
        self.state = []
        self.time_uw[]

